/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projectgui;
import java.awt.CardLayout;
import java.text.DecimalFormat;
import javax.swing.JOptionPane;

/**
 *
 * @author eve__
 */
public class Main extends javax.swing.JFrame {
    Window window;
    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
        c1 = (CardLayout) jPanel1.getLayout();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        spin = new javax.swing.JSpinner();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        NjRadioButton = new javax.swing.JRadioButton();
        SjRadioButton = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        Cbox = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tarea = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        totalb = new javax.swing.JButton();
        Cb = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        distxt = new javax.swing.JTextField();
        jSpinner1 = new javax.swing.JSpinner();
        jLabel6 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        kidbox = new javax.swing.JCheckBox();
        manbox = new javax.swing.JCheckBox();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        total1 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        totaltxt = new javax.swing.JButton();
        clear = new javax.swing.JButton();
        jSpinner3 = new javax.swing.JSpinner();
        jLabel1 = new javax.swing.JLabel();
        jSpinner2 = new javax.swing.JSpinner();
        jScrollPane2 = new javax.swing.JScrollPane();
        area1 = new javax.swing.JTextArea();
        jLabel9 = new javax.swing.JLabel();
        image = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Main");

        jPanel1.setBackground(new java.awt.Color(0, 255, 255));
        jPanel1.setLayout(new java.awt.CardLayout());

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projectgui/interview-pages-suansanook-1.jpg"))); // NOI18N
        jPanel1.add(jLabel14, "card3");

        jPanel2.setBackground(new java.awt.Color(255, 204, 255));
        jPanel2.setLayout(null);

        spin.setModel(new javax.swing.SpinnerNumberModel(1, 0, null, 1));
        jPanel2.add(spin);
        spin.setBounds(510, 120, 60, 30);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 51));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Ticket");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(230, 19, 196, 44);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 255, 204));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("สมาชิก");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(157, 74, 125, 31);

        NjRadioButton.setBackground(new java.awt.Color(0, 255, 255));
        buttonGroup1.add(NjRadioButton);
        NjRadioButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        NjRadioButton.setText("ธรรมดา");
        jPanel2.add(NjRadioButton);
        NjRadioButton.setBounds(317, 74, 69, 25);

        SjRadioButton.setBackground(new java.awt.Color(255, 153, 0));
        buttonGroup1.add(SjRadioButton);
        SjRadioButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        SjRadioButton.setText("VIP ลด20%");
        jPanel2.add(SjRadioButton);
        SjRadioButton.setBounds(413, 74, 100, 25);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 255, 204));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("บัตรเครื่องเล่น");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(157, 123, 125, 30);

        Cbox.setBackground(new java.awt.Color(255, 102, 0));
        Cbox.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Cbox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--", "บัตรเด็ก      70  บาท", "บัตรผู้ใหญ่   100  บาท", "บัตรบ้านหิมะ 120  บาท", "บัตรชมละครสัตว์ 80  บาท" }));
        Cbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CboxActionPerformed(evt);
            }
        });
        jPanel2.add(Cbox);
        Cbox.setBounds(320, 120, 180, 30);

        Tarea.setBackground(new java.awt.Color(0, 0, 0));
        Tarea.setColumns(20);
        Tarea.setForeground(new java.awt.Color(255, 255, 255));
        Tarea.setRows(5);
        jScrollPane1.setViewportView(Tarea);

        jPanel2.add(jScrollPane1);
        jScrollPane1.setBounds(157, 244, 315, 179);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 255, 204));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("รายละเอียด");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(261, 207, 100, 31);

        totalb.setBackground(new java.awt.Color(0, 153, 255));
        totalb.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        totalb.setText("คิดเงิน");
        totalb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalbActionPerformed(evt);
            }
        });
        jPanel2.add(totalb);
        totalb.setBounds(157, 520, 110, 31);

        Cb.setBackground(new java.awt.Color(255, 0, 51));
        Cb.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Cb.setText("Clear");
        Cb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CbActionPerformed(evt);
            }
        });
        jPanel2.add(Cb);
        Cb.setBounds(362, 520, 110, 31);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 255, 204));
        jLabel7.setText("ราคารวม");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(157, 453, 65, 22);

        distxt.setBackground(new java.awt.Color(0, 0, 0));
        distxt.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        distxt.setForeground(new java.awt.Color(255, 255, 255));
        distxt.setEnabled(false);
        jPanel2.add(distxt);
        distxt.setBounds(273, 450, 199, 32);

        jSpinner1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jSpinner1.setModel(new javax.swing.SpinnerDateModel(new java.util.Date(), null, null, java.util.Calendar.MINUTE));
        jPanel2.add(jSpinner1);
        jSpinner1.setBounds(320, 160, 127, 40);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 255, 204));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("วัน/เดือน/ปี เวลา");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(157, 164, 125, 22);

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projectgui/DreamworldEntryTicket.jpg"))); // NOI18N
        jLabel15.setToolTipText("");
        jPanel2.add(jLabel15);
        jLabel15.setBounds(0, 0, 850, 620);

        jPanel1.add(jPanel2, "card2");

        jPanel3.setBackground(new java.awt.Color(51, 255, 0));
        jPanel3.setLayout(null);

        kidbox.setBackground(new java.awt.Color(255, 204, 255));
        kidbox.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        kidbox.setText("บัตรบ้านหิมะ+ละครสัตว์ 150 บาท");
        kidbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kidboxActionPerformed(evt);
            }
        });
        jPanel3.add(kidbox);
        kidbox.setBounds(120, 100, 280, 31);

        manbox.setBackground(new java.awt.Color(255, 204, 51));
        manbox.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        manbox.setText("บัตรเครื่องเล่นทุกรายการไม่จำกัดรอบ 300 บาท");
        jPanel3.add(manbox);
        manbox.setBounds(430, 100, 380, 30);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 0, 51));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Package");
        jPanel3.add(jLabel8);
        jLabel8.setBounds(350, 40, 129, 33);

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("จำนวน");
        jPanel3.add(jLabel10);
        jLabel10.setBounds(270, 170, 180, 29);

        total1.setBackground(new java.awt.Color(0, 0, 0));
        total1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        total1.setForeground(new java.awt.Color(255, 255, 255));
        total1.setEnabled(false);
        jPanel3.add(total1);
        total1.setBounds(480, 260, 141, 28);

        jLabel11.setBackground(new java.awt.Color(51, 255, 51));
        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("ราคา");
        jPanel3.add(jLabel11);
        jLabel11.setBounds(310, 260, 100, 30);

        totaltxt.setBackground(new java.awt.Color(0, 102, 255));
        totaltxt.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        totaltxt.setText("คิดเงิน");
        totaltxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totaltxtActionPerformed(evt);
            }
        });
        jPanel3.add(totaltxt);
        totaltxt.setBounds(210, 570, 120, 31);

        clear.setBackground(new java.awt.Color(255, 0, 51));
        clear.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        clear.setText("Clear");
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });
        jPanel3.add(clear);
        clear.setBounds(440, 570, 110, 31);

        jSpinner3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jSpinner3.setModel(new javax.swing.SpinnerDateModel());
        jPanel3.add(jSpinner3);
        jSpinner3.setBounds(480, 210, 140, 24);

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("วัน/เดือน/ปี เวลา");
        jPanel3.add(jLabel1);
        jLabel1.setBounds(220, 210, 200, 29);

        jSpinner2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jSpinner2.setModel(new javax.swing.SpinnerNumberModel(1, 1, 20, 1));
        jPanel3.add(jSpinner2);
        jSpinner2.setBounds(480, 170, 100, 30);

        area1.setBackground(new java.awt.Color(0, 0, 0));
        area1.setColumns(20);
        area1.setForeground(new java.awt.Color(255, 255, 255));
        area1.setRows(5);
        jScrollPane2.setViewportView(area1);

        jPanel3.add(jScrollPane2);
        jScrollPane2.setBounds(190, 340, 380, 220);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("รายละเอียด");
        jPanel3.add(jLabel9);
        jLabel9.setBounds(240, 300, 124, 29);

        image.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projectgui/wakuwakuland.jpg"))); // NOI18N
        jPanel3.add(image);
        image.setBounds(0, 0, 850, 690);

        jPanel1.add(jPanel3, "card3");

        jPanel4.setBackground(new java.awt.Color(204, 255, 255));
        jPanel4.setLayout(null);

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projectgui/แผนผัง2.jpg"))); // NOI18N
        jPanel4.add(jLabel12);
        jLabel12.setBounds(267, 63, 300, 520);

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 153, 255));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Map");
        jPanel4.add(jLabel13);
        jLabel13.setBounds(370, 10, 80, 40);

        jPanel1.add(jPanel4, "card4");

        jMenu1.setText("Home");
        jMenu1.setToolTipText("");
        jMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu1MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Ticket");
        jMenu2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu2MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu2);

        jMenu3.setText("Package");
        jMenu3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu3MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu3);

        jMenu6.setText("Map");
        jMenu6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu6MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu6);

        jMenu4.setText("Logout");
        jMenu4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu4MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu4);

        jMenu5.setText("Exit");
        jMenu5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu5MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 619, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
int x =1;
    private void totalbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalbActionPerformed
        DecimalFormat dollars = new DecimalFormat("0.00 บาท");
        int i = Cbox.getSelectedIndex();
        int n = (Integer)spin.getValue();
        if(!NjRadioButton.isSelected()&&!SjRadioButton.isSelected())
        {
          JOptionPane.showMessageDialog(null, "กรุณาเลือกสมาชิก",
                "Fail",JOptionPane.ERROR_MESSAGE);   
        }
        if(NjRadioButton.isSelected()||SjRadioButton.isSelected()){
        if (Tarea.getText().equals("")) {
        Tarea.append("===============รายการที่สั่งซื้อ==================\n");
        }
          if (i != -1) {
              switch (i) {
                  case 0:
                      break;
                  case 1:
                      Tarea.append(""+x);
                      Tarea.append(". บัตรเด็ก 70\t"+n+"       บัตร");
                      Tarea.append("\t"+70*n+" บาท");
                      total = total+70*n;
                      x++;
                      break;
                  case 2:
                     Tarea.append(""+x);
                     Tarea.append(". บัตรผู้ใหญ่ 100\t"+n+"       บัตร");
                     Tarea.append("\t"+100*n+" บาท");
                      total = total+100*n;
                      x++;
                      break;
                  case 3:
                       Tarea.append(""+x);
                      Tarea.append(". บัตรบ้านหิมะ 120\t"+n+"      บัตร");
                      Tarea.append("\t"+120*n+" บาท");
                      total = total+120*n;
                      x++;
                      break;
                  case 4:
                       Tarea.append(""+x);
                     Tarea.append(". บัตรละครสัตว์ 80\t"+n+"       บัตร");
                     Tarea.append("\t"+80*n+" บาท");
                      total = total+80*n;
                      x++;
                      break;
              }
        }
        double discount;    
        if (SjRadioButton.isSelected()) {
            discount = 0.20;
        } else {
            discount = 0.00;
        }
        if (SjRadioButton.isSelected()) {
            Tarea.append("\nท่านได้รับส่วนลด 20% \n");
            Tarea.append("----------------------------------------------------------\n");
        } else {
            Tarea.append("\n----------------------------------------------------------\n");
        }
        double result = total * (1 - discount);
        distxt.setText(String.valueOf(dollars.format(result)));
        }
         
    }//GEN-LAST:event_totalbActionPerformed
    int total = 0;
    private void CboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CboxActionPerformed
   
// TODO add your handling code here:
    }//GEN-LAST:event_CboxActionPerformed

    private void jMenu2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu2MouseClicked
        // TODO add your handling code here:
       c1.show(jPanel1, "card2");
    }//GEN-LAST:event_jMenu2MouseClicked

    private void CbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CbActionPerformed
        // TODO add your handling code here:
        total = 0;
        Tarea.setText("");
        distxt.setText("");
        Cbox.setSelectedIndex(0);
        SjRadioButton.setSelected(false);
        NjRadioButton.setSelected(true);
        spin.setValue(1);
        x = 1;
    }//GEN-LAST:event_CbActionPerformed

    private void jMenu4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu4MouseClicked
        // TODO add your handling code here:
        window = new Window();
        window.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jMenu4MouseClicked

    private void jMenu3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu3MouseClicked
        // TODO add your handling code here:
        c1.show(jPanel1, "card3");
    }//GEN-LAST:event_jMenu3MouseClicked

    private void jMenu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu1MouseClicked
        // TODO add your handling code here:
        c1.first(jPanel1);
    }//GEN-LAST:event_jMenu1MouseClicked

    private void jMenu5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu5MouseClicked
        // TODO add your handling code here:
        System.exit(0);
        super.dispose();
    }//GEN-LAST:event_jMenu5MouseClicked

    private void kidboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kidboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kidboxActionPerformed
int total3 = 0;
int y =1;
    private void totaltxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totaltxtActionPerformed
        int qty;
        qty = (Integer)jSpinner2.getValue();
        DecimalFormat dollars = new DecimalFormat("0.00 Baht");
        if(!kidbox.isSelected()&&!manbox.isSelected()){
         JOptionPane.showMessageDialog(null, "กรุณาเลือก Package",
                "Fail",JOptionPane.ERROR_MESSAGE);   
        }
        if(kidbox.isSelected()||manbox.isSelected()){
            if (area1.getText().equals("")) {
            area1.append("===============รายการที่สั่งซื้อ==================\n");
            }
        if(kidbox.isSelected()&&!manbox.isSelected()) {
            total3= total3+150*qty;
            area1.append(""+y);
            area1.append(" .บัตรบ้านหิมะ+ละครสัตว์ 150\t    จำนวน        "+qty+" ใบ");
            area1.append(" "+150*qty+" บาท\n");
            area1.append("----------------------------------------------------------------------------------------\n");
            y++;
        }
        if (manbox.isSelected()&&!kidbox.isSelected()) {
            total3= total3+300*qty;
            area1.append(""+y);
            area1.append(" .บัตรเครื่องเล่นทุกรายการไม่จำกัดรอบ 300  จำนวน\t"+qty+" ใบ");
            area1.append(" "+300*qty+" บาท\n");
            area1.append("----------------------------------------------------------------------------------------\n");
            y++;
        }
        if(kidbox.isSelected()&&manbox.isSelected()){
            total3= total3+150*qty;
            area1.append(""+y);
            area1.append(" .บัตรบ้านหิมะ+ละครสัตว์ 150\t    จำนวน        "+qty+" ใบ");
            area1.append(" "+150*qty+" บาท\n");
            area1.append("----------------------------------------------------------------------------------------\n");
            y++;
            total3= total3+300*qty;
            area1.append(""+y);
            area1.append(" .บัตรเครื่องเล่นทุกรายการไม่จำกัดรอบ 300  จำนวน\t"+qty+" ใบ");
            area1.append(" "+300*qty+" บาท\n");
            area1.append("----------------------------------------------------------------------------------------\n");
            y++;
        }
        total1.setText(String.valueOf(dollars.format(total3)));
        }
     
    }//GEN-LAST:event_totaltxtActionPerformed

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
        // TODO add your handling code here:
        kidbox.setSelected(false);
        manbox.setSelected(false);
        total1.setText("");
        jSpinner2.setValue(1);
        area1.setText("");
        total3 = 0;
        y=1;
    }//GEN-LAST:event_clearActionPerformed

    private void jMenu6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu6MouseClicked
        // TODO add your handling code here:
        c1.show(jPanel1, "card4");
    }//GEN-LAST:event_jMenu6MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Cb;
    private javax.swing.JComboBox<String> Cbox;
    private javax.swing.JRadioButton NjRadioButton;
    private javax.swing.JRadioButton SjRadioButton;
    private javax.swing.JTextArea Tarea;
    private javax.swing.JTextArea area1;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton clear;
    private javax.swing.JTextField distxt;
    private javax.swing.JLabel image;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JSpinner jSpinner2;
    private javax.swing.JSpinner jSpinner3;
    private javax.swing.JCheckBox kidbox;
    private javax.swing.JCheckBox manbox;
    private javax.swing.JSpinner spin;
    private javax.swing.JTextField total1;
    private javax.swing.JButton totalb;
    private javax.swing.JButton totaltxt;
    // End of variables declaration//GEN-END:variables
private CardLayout c1;
}
